/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("cus.crm.myaccounts.util.formatter");jQuery.sap.require("sap.ca.ui.model.format.DateFormat");jQuery.sap.require("sap.ca.ui.model.format.NumberFormat");jQuery.sap.require("sap.ca.ui.model.format.AmountFormat");cus.crm.myaccounts.util.formatter={};
cus.crm.myaccounts.util.formatter.formatMediumTimeInterval=function(f,t){if(f&&t){if(f.getYear()==t.getYear()&&f.getMonth()==t.getMonth()&&f.getDay()==t.getDay())return sap.ca.ui.model.format.DateFormat.getDateInstance({style:"medium"}).format(f);else{return sap.ca.ui.model.format.DateFormat.getDateInstance({style:"medium"}).format(f)+" - "+sap.ca.ui.model.format.DateFormat.getDateInstance({style:"medium"}).format(t)}}else{return""}};
cus.crm.myaccounts.util.formatter.formatMediumDate=function(v){if(v){return sap.ca.ui.model.format.DateFormat.getDateInstance({style:"medium"}).format(v)}else{return""}};
cus.crm.myaccounts.util.formatter.formatLongDate=function(v){if(v){return sap.ca.ui.model.format.DateFormat.getDateInstance({style:"long"}).format(v)}else{return""}};
cus.crm.myaccounts.util.formatter.formatShortDate=function(v){if(v){return sap.ca.ui.model.format.DateFormat.getDateInstance({style:"short"}).format(v)}else{return""}};
cus.crm.myaccounts.util.formatter.formatAmounts=function(v,c){if(v>0){return sap.ca.ui.model.format.AmountFormat.FormatAmountStandardWithCurrency(v,c)}return""};
cus.crm.myaccounts.util.formatter.formatShortAmounts=function(v,c){if(v>0){return sap.ca.ui.model.format.AmountFormat.FormatAmountShortWithCurrency(v,c)}return""};
cus.crm.myaccounts.util.formatter.formatShortNumber=function(v,c){if(v>0){return sap.ca.ui.model.format.AmountFormat.FormatAmountShort(v,c)}return""};
cus.crm.myaccounts.util.formatter.formatEmployeeResponsible=function(f){if(f){return f}else{return sap.ca.scfld.md.app.Application.getImpl().getResourceBundle().getText("EMPLOYEE_RESPONSIBLE")}};
cus.crm.myaccounts.util.formatter.formatMediumDateTime=function(v){if(v){return sap.ca.ui.model.format.DateFormat.getDateTimeInstance({style:"medium"}).format(v)}else{return""}};
cus.crm.myaccounts.util.formatter.formatStartDate=function(v){if(v){var d=sap.ca.ui.model.format.DateFormat.getDateInstance({style:"medium"}).format(v);return sap.ca.scfld.md.app.Application.getImpl().getResourceBundle().getText("STARTING",[d])}else{return""}};
cus.crm.myaccounts.util.formatter.formatCloseDate=function(v){if(v){var d=sap.ca.ui.model.format.DateFormat.getDateInstance({style:"medium"}).format(v);return sap.ca.scfld.md.app.Application.getImpl().getResourceBundle().getText("CLOSING",[d])}else{return""}};
cus.crm.myaccounts.util.formatter.formatDueDate=function(v){if(v){var d=sap.ca.ui.model.format.DateFormat.getDateInstance({style:"medium"}).format(v);return sap.ca.scfld.md.app.Application.getImpl().getResourceBundle().getText("DUE",[d])}else{return""}};
cus.crm.myaccounts.util.formatter.mimeTypeFormatter=function(v){switch(v){case'application/vnd.openxmlformats-officedocument.presentationml.presentation':case'application/vnd.ms-powerpoint':return'pptx';break;case'application/msword':case'application/vnd.openxmlformats-officedocument.wordprocessingml.document':return'doc';break;case'application/vnd.ms-excel':case'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':return'xls';break;case'image/jpeg':case'image/png':case'image/tiff':case'image/gif':return'jpg';break;case'application/pdf':return'pdf';break;case'text/plain':return'txt';break;default:return'unknown'}};
cus.crm.myaccounts.util.formatter.getRelativePathFromURL=function(a){var u=document.createElement('a');u.href=a;if(u.pathname.substring(0,1)=="/")return u.pathname;else return"/"+u.pathname};
cus.crm.myaccounts.util.formatter.logoUrlFormatter=function(m,c){if(m){return cus.crm.myaccounts.util.formatter.getRelativePathFromURL(m)}else{switch(c){case'1':return"sap-icon://person-placeholder";break;case'2':return"sap-icon://factory";break;case'3':return"sap-icon://group";break;default:return"sap-icon://factory"}}};
cus.crm.myaccounts.util.formatter.urlFormatter=function(v){var s,S,a,b,u,c;s=jQuery.sap.getUriParameters().get("sap-server");S=jQuery.sap.getUriParameters().get("sap-host");a=jQuery.sap.getUriParameters().get("sap-host-http");b=jQuery.sap.getUriParameters().get("sap-client");u=URI(location.protocol+"//"+location.hostname+(location.port?':'+location.port:'')+cus.crm.myaccounts.util.formatter.getRelativePathFromURL(v));c=location.protocol.replace(':','');if(c!==u.protocol()){u.protocol(c)}if(s){u.addSearch('sap-server',s)}if(S){u.addSearch('sap-host',S)}if(a){u.addSearch('sap-host-http',a)}if(b){u.addSearch('sap-client',b)}return u.toString()};
cus.crm.myaccounts.util.formatter.logoVisibilityFormatter=function(m){if(m){return true}else{return false}};
cus.crm.myaccounts.util.formatter.locationFormatter=function(c,C){if(!c){return C}else if(!C){return c}else{return sap.ca.scfld.md.app.Application.getImpl().getResourceBundle().getText("LOCATION",[c,C])}};
cus.crm.myaccounts.util.formatter.comaSeparator=function(v,a){var s=v;if(a)return s?s+", "+a:a;return s};
cus.crm.myaccounts.util.formatter.sleshSeparator=function(v,a){var s=v;if(a)return s?s+" / "+a:a;return s};
cus.crm.myaccounts.util.formatter.AccountNameFormatter=function(f,n){if(f){return f}else{return n}};
cus.crm.myaccounts.util.formatter.isEqual=function(v,a){if(typeof(v)=="string"&&typeof(a)=="string"){return v.valueOf()==a.valueOf()}else{return v==a}};
cus.crm.myaccounts.util.formatter.isUnequal=function(v,a){if(typeof(v)=="string"&&typeof(a)=="string"){return v.valueOf()!=a.valueOf()}else{return v!=a}};
cus.crm.myaccounts.util.formatter.AccountSpecificText=function(t,a,b,c){switch(c){case cus.crm.myaccounts.util.Constants.accountCategoryPerson:return t;break;case cus.crm.myaccounts.util.Constants.accountCategoryCompany:return a;break;case cus.crm.myaccounts.util.Constants.accountCategoryGroup:return b;break}};
