/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("hcm.emp.payslip.controls.PDFViewer");jQuery.sap.require("sap.ui.core.library");jQuery.sap.require("sap.ui.core.RenderManager");sap.ui.core.Control.extend("hcm.emp.payslip.controls.PDFViewer",{metadata:{properties:{"src":{type:"string",group:"Misc"},"errorMessage":{type:"string",group:"Misc"},"setPdfData":{type:"string",group:"Misc"}},events:{"begin":{},"complete":{}}}});
hcm.emp.payslip.controls.PDFViewer.prototype.exit=function(){jQuery.sap.log.debug("exit "+this.getSrc());this.UnloadPdf();this.ClearPdfData()};
hcm.emp.payslip.controls.PDFViewer.prototype.Show=function(l){var s=this.getSrc();if(null==s||s.length==0){return}if(!this._pdfData){this.fireBegin();l.LoadPdf(s,jQuery.proxy(this.setPdfData,this),jQuery.proxy(this.showErrorMessage,this))}else{this.RenderPdf()}};
hcm.emp.payslip.controls.PDFViewer.prototype.ClearPdfData=function(){this._pdfData=null};
hcm.emp.payslip.controls.PDFViewer.prototype.UnloadPdf=function(){if(this._pdf!=null){jQuery.sap.log.debug("UnloadPdf "+this.getSrc());this._pdf.destroy();this._pdf=null;$(this.getDomRef()).empty()}};
hcm.emp.payslip.controls.PDFViewer.prototype.setPdfData=function(d){this._pdfData=d;this.RenderPdf()};
hcm.emp.payslip.controls.PDFViewer.prototype.showErrorMessage=function(r){var e=(null!=r)?null:JSON.parse(r)};
hcm.emp.payslip.controls.PDFViewer.prototype.RenderPdf=function(){var i=this.getDomRef(),t=this,c=[];jQuery.sap.log.debug("RenderPdf "+this.getSrc());if(i.childNodes!=null&&i.childNodes.length>0){setTimeout(function(){jQuery.sap.log.debug("The control is already rendered");t.fireComplete()},500);return}var p=jQuery.sap.getModulePath("hcm.emp.payslip")+"/ext/pdfjs/pdf.js";jQuery.sap.require("hcm.emp.payslip.ext.pdfjs.pdf");if(PDFJS.workerSrc!=p){PDFJS.workerSrc=p}PDFJS.getDocument(this._pdfData).then(function getPdfForm(a){t._pdf=a;var v=i,b=1;t.renderPage(v,a,b++,function pageRenderingComplete(){if(b>a.numPages){jQuery.sap.log.debug("renderPage complete");t.fireComplete();return}jQuery.sap.log.debug("render another page");t.renderPage(v,a,b++,pageRenderingComplete)},c)})};
hcm.emp.payslip.controls.PDFViewer.prototype.renderPage=function(d,p,a,c){p.getPage(a).then(function(b){jQuery.sap.log.debug("renderingPage "+a);var e,v,f,g,s,h;s=2;if(null==d.offsetParent||null==d.offsetParent.clientWidth){jQuery.sap.log.debug("invalid offsetParent");return}e=d.offsetParent.clientWidth;v=b.getViewport(1);f=v.width;g=jQuery.device.is.phone?1:e/f;h=b.getViewport(s*g);var i=h.width;var j=h.height;var k=document.createElement('div');k.className='pdfpage';if(jQuery.device.is.phone){k.style.width=i+'px';k.style.height=j+'px'}else{k.style.width=i/s+'px';k.style.height=j/s+'px'}d.appendChild(k);var l=document.createElement('canvas');var m=l.getContext('2d');l.width=i;l.height=j;if(jQuery.device.is.phone){l.style.width=i+'px';l.style.height=j+'px'}else{l.style.width=i/s+'px';l.style.height=j/s+'px'}var r={canvasContext:m,viewport:h};b.render(r).then(function(){k.appendChild(l);c()})})};
