/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("sap.crm.MDualSlider");jQuery.sap.require("sap.m.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.crm.MDualSlider",{metadata:{publicMethods:["stepUp","stepDown"],library:"sap.m",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Appearance",defaultValue:'100%'},"enabled":{type:"boolean",group:"Behavior",defaultValue:true},"visible":{type:"boolean",group:"Appearance",defaultValue:true},"name":{type:"string",group:"Misc",defaultValue:null},"value":{type:"float",group:"Data",defaultValue:0},"value2":{type:"float",group:"Data",defaultValue:1}},aggregations:{units:{type:"sap.crm.MDualSliderLabel",multiple:true,singularName:"unit"}},events:{"change":{},"liveChange":{}}}});sap.crm.MDualSlider._bIsRTL=sap.ui.getCore().getConfiguration().getRTL();sap.crm.MDualSlider.M_EVENTS={'change':'change','liveChange':'liveChange'};jQuery.sap.require("sap.ui.core.EnabledPropagator");sap.ui.core.EnabledPropagator.apply(sap.crm.MDualSlider.prototype,[true]);
sap.crm.MDualSlider.prototype.onBeforeRendering=function(){var m=0,u=this.getUnits(),M=u.length-1;var s=1,b=false,e=false;if(m>=M){b=true;e=true;jQuery.sap.log.warning("Warning: "+"Property wrong min: "+m+" >= max: "+M+" on ",this)}if(s<=0){jQuery.sap.log.warning("Warning: "+"The step could not be negative on ",this);s=1;this.setProperty("step",s,true)}if(s>(M-m)&&!b){e=true;jQuery.sap.log.warning("Warning: "+"Property wrong step: "+s+" > max: "+M+" - "+"min: "+m+" on ",this)}if(!e){var l=this.getValue(),r=this.getValue2();this.setValue(l).setValue2(r);l=this.getValue();r=this.getValue2();var w=r-l,R=this._getPercentFromValue(r);this._fValue=this._getPercentFromValue(l);this._fValue2=this._getPercentFromValue(r);this._fWidth=this._getPercentFromValue(w);R=r==M?100-(R+1):100-(R+3);this._fValueText=this._getPercentFromValue(l)-1;this._fValue2Text=R}this._bDisabled=!this.getEnabled()};
sap.crm.MDualSlider.prototype.onAfterRendering=function(){this._$SliderContainer=this.$();this._$Slider=this._$SliderContainer.children(".sapcrmMsli");this._$ProgressIndicator=this._$Slider.children(".sapcrmMsliProgress");this._$Handle=this._$Slider.children(".sapcrmMsliHandle");this._$Lhandle=this._$Handle.first();this._$Rhandle=this._$Handle.last();this._$SliderContainer.css("visibility","")};
sap.crm.MDualSlider.prototype.ontouchstart=function(e){var t=jQuery(e.target),m=0,M=this.getUnits().length-1;e.originalEvent._sapui_handledByControl=true;if(e.targetTouches.length>1||this._bDisabled){return}this._recalculateStyles();this._fDiffX=this._fSliderPaddingLeft;if(t.attr("id")=="left"){this._fStartValue=this.getValue();this._handle_hold="left";this._$Lhandle.css("background-color","rgba(0, 124, 192, 0.3)");this._$Lhandle.css("border","0.125rem solid #007cc0")}else if(t.attr("id")=="right"){this._fStartValue=this.getValue2();this._handle_hold="right";this._$Rhandle.css("background-color","rgba(0, 124, 192, 0.3)");this._$Rhandle.css("border","0.125rem solid #007cc0")}else if(t.attr("id")=="mSlider_bar"){this._handle_hold="bar";this._$Lhandle.css("background-color","rgba(0, 124, 192, 0.3)");this._$Lhandle.css("border","0.125rem solid #007cc0");this._$Rhandle.css("background-color","rgba(0, 124, 192, 0.3)");this._$Rhandle.css("border","0.125rem solid #007cc0");var i=(e.targetTouches[0].pageX-this._fDiffX-this._fSliderOffsetLeft)/this._fSliderWidth;this.fNewValue_start=m+(i*(M-m));if(this._bIsRTL)this.fNewValue_start=this._convertValueToRTL(this.fNewValue_start)}this.fireLiveChange({value:this.getValue(),value2:this.getValue2()})};
sap.crm.MDualSlider.prototype.ontouchmove=function(e){if(this._bDisabled){return}var m=0,M=this.getUnits().length-1,i=(e.targetTouches[0].pageX-this._fDiffX-this._fSliderOffsetLeft)/this._fSliderWidth;var n=m+(i*(M-m));if(this._bIsRTL)n=this._convertValueToRTL(n);if(this._handle_hold=="left"){this.setValue(n)}else if(this._handle_hold=="right"){this.setValue2(n)}else if(this._handle_hold=="bar"){var b=(e.targetTouches[0].pageX-this._fDiffX-this._fSliderOffsetLeft)/this._fSliderWidth;this.fNewValue_end=m+(b*(M-m));if(this._bIsRTL)this.fNewValue_end=this._convertValueToRTL(this.fNewValue_end);var l=this.getValue(),r=this.getValue2(),d=this.fNewValue_end-this.fNewValue_start,s=1;var N=l+d,f=Math.abs(N%s),a=r+d,c=Math.abs(a%s);if(f*2>=s){N+=(s-f);a+=(s-c)}else{N-=f;a-=c}if(l!=m||N>l){if(r!=M||a<r)this.setValue(N).setValue2(a)}if(l!==N)this.fNewValue_start=this.fNewValue_end}this.fireLiveChange({value:this.getValue(),value2:this.getValue2()})};
sap.crm.MDualSlider.prototype.ontouchend=function(e){if(this._handle_hold=="left"){this._$Lhandle.css("background-color","");this._$Lhandle.css("border","")}else if(this._handle_hold=="right"){this._$Rhandle.css("background-color","");this._$Rhandle.css("border","")}else if(this._handle_hold=="bar"){this._$Lhandle.css("background-color","");this._$Lhandle.css("border","");this._$Rhandle.css("background-color","");this._$Rhandle.css("border","")}if(this._bDisabled){return}if(this._fStartValue!==this.getValue()){this.fireChange({value:this.getValue(),value2:this.getValue2()})}delete this._fDiffX;delete this._fStartValue;this._handle_hold=null;var c=sap.ca.scfld.md.app.Application.getImpl();c.oCurController.FullCtrl.reRenderTopNSlider=true};
sap.crm.MDualSlider.prototype.ontouchcancel=sap.crm.MDualSlider.prototype.ontouchend;
sap.crm.MDualSlider.prototype._recalculateStyles=function(){this._fSliderWidth=this._$SliderContainer.width();this._fSliderPaddingLeft=parseFloat(this._$SliderContainer.css("padding-left"));this._fSliderOffsetLeft=this._$SliderContainer.offset().left;this._fHandleWidth=this._$Handle.width()};
sap.crm.MDualSlider.prototype._getPercentFromValue=function(v){var m=0,M=this.getUnits().length-1;return((v-m)/(M-m))*100};
sap.crm.MDualSlider.prototype._convertValueToRTL=function(n){var m=0,M=this.getUnits().length-1;return M-(m+n)};
sap.crm.MDualSlider.prototype._validateN=function(n){var t=typeof n;if(t==="undefined")return 1;else if(t!=="number"){jQuery.sap.log.warning('Warning: n needs to be a number',this);return 0}else if(Math.floor(n)===n&&isFinite(n)){return n}else{jQuery.sap.log.warning('Warning: n needs to be a finite interger',this);return 0}};
sap.crm.MDualSlider.prototype._setValue=function(n){var m=0,u=this.getUnits(),M=u.length-1,s=1,l=this.getValue(),r=this.getValue2(),f=Math.abs(n%s),N;if(typeof n!=="number"||!isFinite(n)){jQuery.sap.log.error("Error:",'"fNewValue" needs to be a finite number of',this);return this}if(f*2>=s)n+=(s-f);else n-=f;n=n>M?M:n<m?m:n;if(this._handle_hold!=="bar"&&this._handle_hold!=undefined){if(n>=r){n=r-1}}n=Number(n.toFixed(5));if(n==r&&this._handle_hold!=="bar")return this;this.setProperty("value",n,true);this._sValueText=" ";this._sValueText=u[n].getValue();if(l===this.getValue())return this;if(this._$SliderContainer){l=this.getValue();N=this._getPercentFromValue(n);var w=r-l,L=this._getPercentFromValue(l),a=this._bIsRTL?"right":"left";this._fWidth=this._getPercentFromValue(w);this._$ProgressIndicator[0].style.width=this._fWidth+"%";this._$ProgressIndicator[0].style[a]=L+"%";$("#left_text").css("margin-"+a,L+"%");$("#left_text").text(this._sValueText);this._$Handle[0].style[a]=N+"%";this._$Handle[0].title=this._sValueText}return this};
sap.crm.MDualSlider.prototype._setValue2=function(n){var m=0,u=this.getUnits(),M=u.length-1,s=1,l=this.getValue(),r=this.getValue2(),f=Math.abs(n%s),N;if(typeof n!=="number"||!isFinite(n)){jQuery.sap.log.error("Error:",'"fNewValue" needs to be a finite number of',this);return this}if(f*2>=s)n+=(s-f);else n-=f;n=n>M?M:n<m?m:n;if((this._handle_hold!=="bar")&&(this._handle_hold!=undefined)){if(n<=l){n=l+1;return}}n=Number(n.toFixed(5));if(n==l)return this;this.setProperty("value2",n,true);this._sValue2Text=" ";this._sValue2Text=u[n].getValue();if(r===this.getValue2())return this;if(this._$SliderContainer){r=this.getValue2();N=this._getPercentFromValue(n);var w=r-l,R=this._getPercentFromValue(r),L,a;if(this._bIsRTL){L="right";a="left"}else{L="left";a="right"}this._fWidth=this._getPercentFromValue(w);this._$ProgressIndicator[0].style.width=this._fWidth+"%";this._$ProgressIndicator[0].style[a]=R+"%";R=n==M?100-(R+1):100-(R+3);$("#right_text").css("margin-"+a,R+"%");$("#right_text").text(this._sValue2Text);this._$Handle[1].style[L]=N+"%";this._$Handle[1].title=this._sValue2Text}return this};
sap.crm.MDualSlider.prototype.stepUp=function(n){return this.setValue(this.getValue()+(this._validateN(n)*1))};
sap.crm.MDualSlider.prototype.stepDown=function(n){return this.setValue(this.getValue()-(this._validateN(n)*1))};
sap.crm.MDualSlider.prototype.setValue=function(n){this.setValue=this._setValue;return this.setProperty("value",n,true)};
sap.crm.MDualSlider.prototype.setValue2=function(n){this.setValue2=this._setValue2;return this.setProperty("value2",n,true)};
/*
 * ! SAP UI development toolkit for HTML5 (SAPUI5)
 * 
 * (c) Copyright 2009-2014 SAP SE. All rights reserved
 */
